services:
  app:
    build:
      context: ./sidekiq-book
    tty: true
    stdin_open: true
    volumes:
      - ./sidekiq-book/:/app/
    command: bash -c "rm -rf /app/tmp/pids/server.pid &&
                      rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    depends_on:
      - db
      - api
  api:
    build:
      context: ./fake-api-server
    tty: true
    stdin_open: true
    volumes:
      - ./fake-api-server/:/app/
    command: bash -c "bin/run"
    ports:
      - 3001:4000

  sidekiq:
    build:
      context: ./sidekiq-book
    tty: true
    stdin_open: true
    volumes:
      - ./sidekiq-book/:/app/
    command: bash -c "bundle exec sidekiq"
    depends_on:
      - app

  redis:
    image: redis
    restart: unless-stopped
  db:
    image: postgres:15
    volumes:
      - ./tmp/db:/var/lib/postgres/data
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
