#!/bin/bash

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${0}" )" > /dev/null 2>&1 && pwd )

. "${SCRIPT_DIR}/dx.sh.lib"

require_command "docker"
require_command "rsync"
require_command "realpath"

ensure_docker_compose_env

if docker buildx ls | grep "^multi-arch " > /dev/null 2>&1 ; then
  log "🥯" "multi-arch builder exists already"
else
  log "🥯" "multi-arch builder doesn't exist. Creating..."
  docker buildx create --name=multi-arch --bootstrap --use
fi
log "🧰" "Using multi-arch builder"
docker buildx use multi-arch

log "🐋" "Building and pushing images to Docker Hub"
docker buildx build \
  --file Dockerfile \
  --tag "davetron5000/fake-api-server:1.2.0" \
  --platform=linux/arm64,linux/amd64 \
  --push \
  ./

BOOK_REPO_CODE=$(realpath ${SCRIPT_DIR}/../../dcsidekiq/Book/code)
log "🔄" "Re-syncing to book repo '${BOOK_REPO_CODE}'"
rsync -l --exclude='/.git' --delete -r . ${BOOK_REPO_CODE}/fake-api-server
# vim: ft=bash
